# Location
#
# Provide your location in decimal degrees (e.g. lat=12.34)
lat=
lon=

# Units
#
# Options are metric/standard/imperial
units=

# Backend
#
# You can choose between owm (OpenWeatherMap) and meteo (Open-Meteo)
# If you use owm, you will need to register for an API key from their OneCall
# 3.0 service
# Open-Meteo does not require an API key
backend=
appid=

# Width guarding
#
# If you want to use a tooltip font-size other than 16px, you may run into 
# issues with the text wrapping improperly inside the tooltip. To fix this, you
# can provide an integer argument on the widthguard line below. This is the 
# number of box-drawing characters that will be inserted on a line below the 
# header line, in order to force the tooltip to grow wider. By default, this
# line is rendered in black so as to be invisible on the default Waybar tooltip
# background. You can provide a color argument on the guardcolor line to make
# it visible, if you want (e.g. guardcolor=white).
#
# You may have to experiment. In my testing, a reasonable starting value may be
# around 68.
widthguard=
guardcolor=
